### ISSUE TITLE
Robotics update checklist

### ISSUE THREAD

**Issue by Elijahrane** [arcadia-station/arcadia-station#135]
## Description

- [x] Cleanbots
- [x] Honkbots
- [x] Robotics tech
- [x] Medbots
- [x] Make bots destructible
- [x] Roboticist job
- [x] Robotics vendor
- [x] fix bot mover cbt
- [ ] polish up some of the construction graphs
- [ ] optimize ai at least a bit

**Comment by wolfy9011** [comment]
why
why honkbots

https://user-images.githubusercontent.com/72601626/169471821-d2da6cb8-23e9-4ea0-94a5-2d8c5436e5fa.mp4
