### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by Elijahrane** [arcadia-station/arcadia-station#6]
## Description

**Features**
- [x] Vomiting - https://github.com/Nyanotrasen/Nyanotrasen/pull/14
- [x] Goon Farting - https://github.com/Nyanotrasen/Nyanotrasen/pull/24
- [x] Killer Tomatoes
- [x] 1 gorillion weaboo outfits
- [x] Ebows - https://github.com/Nyanotrasen/Nyanotrasen/pull/33
- [x] Stethoscope - https://github.com/Nyanotrasen/Nyanotrasen/pull/34
- [x] Lean - https://github.com/Nyanotrasen/Nyanotrasen/pull/46

**Jobs**
- [x] Boxer - https://github.com/arcadia-station/arcadia-station/pull/3
- [x] Paramedic - https://github.com/arcadia-station/nyanotrasen/pull/7
- [x] Mail Carrier - https://github.com/Nyanotrasen/Nyanotrasen/pull/25
- [x] Detective - https://github.com/Nyanotrasen/Nyanotrasen/pull/29
- [x] Cull librarian, possibly others - https://github.com/arcadia-station/arcadia-station/issues/5

**Species**
- [x] Felinid - https://github.com/Nyanotrasen/Nyanotrasen/pull/15

**Maps**
- [x] Convert Atlas as our premier, default low-pop map - https://github.com/Nyanotrasen/Nyanotrasen/pull/8

**Server Setup**
- [x] Set up a CDN
- [x] Stupid fucking script to generate manifest.json for SS14.Watchdog
- [x] Find out why SS14.Watchdog doesn't fucking work
- [x] Postgres
- [x] Get listed on the hub
- [x] Grafana, Loki, Prometheus
- [x] SS14.Admin
- [x] Cull bad maps
- [x] Force traitor as the only gamemode
- [x] Appoint additional admins
- [x] Unique rules.txt
- [x] Get a different splash screen holy shit
