### ISSUE TITLE
Research Update Checklist

### ISSUE THREAD

**Issue by Elijahrane** [arcadia-station/arcadia-station#69]
## Description

- [x] QSIs
- [x] Shrink rays
- [x] Holosign projectors
- [x] Holofans
- [x] Advanced mops
- [x] Bags of holding mechanics
- [x] Bluespace tier tech
- [x] Add logging to bags of holding
- [x] Fix decloner sprite errors
- [x] Unique shrink ray sprite/sound
- [x] Make QSI teleportation more robust
- [x] Make shrink ray more robust
- [x] Update mass and BB on size changed items
- [x] Service & Engineering Techfabs
- [x] Effects on damage taken on size changed
- [x] Research Point Disk Item (Insert into research server for + x amount of points)
- [x] Some method to acquire RPDs
- [x] Bluespace material
- [x] Update spacetime crating stuff to require bluespace
- [x] Some method to acquire bluespace
- [x] Scientist specific methods for bluespace and RPDs
- [ ] Split out shrink ray system into a more generic size system
- [x] Lockboxes should display which access they require
- [x] Reenable popups on qsis and bags of holding once that stupid crash is fixed upstream
- [x] Redo entire science department roles / mapping
- [x] Fix shrink ray sprites not resetting
- [x] Put unused lathe prototypes in so stuff is acquirable
- [x] Change growth ray to a smaller factor so it breaks less
- [x] Size change needs to not set a new original size if you are already size changed
- [ ] Being shrunken should change your collision layers/mask
- [x] Shrunken people shouldn't be able to pick each other up
- [x] Holofan needs to give more info on charge status
- [x] Mailman hat shouldnt block hair
- [x] Oracle rewards should be 100% chance of 5k research PLUS 15% of a bluespace crystal
- [x] Shrunken people need to be able to resist
- [x] Shock collar should use new signal standards
- [x] You should be able to use shrink ray on yourself
- [x] Shrink should scale camera zoom
- [x] Holofans should trap the air in their tiles
- [x] Atlas needs mapped uniform printer
- [x] Check atlas med/rnd connection
- [x] Mystagogue needs det and chapel access
- [x] R&D should start with some bluespace crystals
- [x] Boxer needs service access
- [x] Theobromine got reverted accidentally
- [x] QSIs need to use global position and be usable across grids
